apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: christanyk-app
spec:
  project: default
  source:
    repoURL: "https://github.com/chrisTanYK/argocd0513.git"
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: christanyk-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

